// File: SinGenerator.v
// Generated by MyHDL 0.9.0
// Date: Sat Oct  7 14:50:45 2017


`timescale 1ns/10ps

module SinGenerator (
    KONSTANT_FACTOR_in,
    SinValue_out,
    clk,
    rst
);


input signed [30:0] KONSTANT_FACTOR_in;
output signed [30:0] SinValue_out;
wire signed [30:0] SinValue_out;
input clk;
input rst;

reg signed [30:0] Reg_T1;
reg signed [30:0] Reg_T0;






assign SinValue_out = Reg_T1;


always @(posedge clk, negedge rst) begin: SINGENERATOR_LOGICCP
    if ((rst == 0)) begin
        Reg_T0 <= ((2 ** 29) - 1);
        Reg_T1 <= 478355485;
    end
    else begin
        Reg_T0 <= Reg_T1;
        Reg_T1 <= ($signed((KONSTANT_FACTOR_in * Reg_T1) >>> (29 - 1)) - Reg_T0);
    end
end

endmodule
